### ISSUE TITLE
Return all data of the events array

### ISSUE THREAD

**Issue by Acariste** [lexkrstn/jquery-sked-tape#1]
Hello,
i have question, it's possible to return all the content of the skedTape like all events with the function GetEvents() ? i try to access to the function but nothing seem to work.

Thank you

**Comment by lexkrstn** [comment]
Yes, you just have to invoke it though the class instance like this:
```javascript
var skedTape = $skedTape.data('sked-tape'); // getting the instance
var events = skedTape.getEvents();
```

**Comment by Acariste** [comment]
Thank you very mutch for your fast answer it work well !
