### ISSUE TITLE
dates topbar does not go all the way to the end of time interval in modal

### ISSUE THREAD

**Issue by ad17633** [lexkrstn/jquery-sked-tape#10]
I trying to display the scheduler in a bootstrap modal. The topbar with the dates does not stretch all the way to the end of the selected time interval. Instead all dates are clustered together. Scrolling left shows empty white space at the top. Please take a look at the attached screenshots. 

Thanks in advance,
AD

![screen shot 2019-03-03 at 6 51 47 pm](https://user-images.githubusercontent.com/5654374/53704970-c77ad880-3de6-11e9-90a6-c0d73c13ec30.png)
![screen shot 2019-03-03 at 6 52 24 pm](https://user-images.githubusercontent.com/5654374/53704971-c77ad880-3de6-11e9-99e4-87bf76b64644.png)
![screen shot 2019-03-03 at 6 52 45 pm](https://user-images.githubusercontent.com/5654374/53704972-c8136f00-3de6-11e9-80e3-45f90b448d2b.png)
![screen shot 2019-03-03 at 6 53 09 pm](https://user-images.githubusercontent.com/5654374/53704973-c8136f00-3de6-11e9-8c08-b94eb65fc19c.png)

**Comment by tokidoki11** [comment]
I found a similar things happening on bootstrap tab where I load 2 instances at the sametime
I kinda forgot the workaround but have you tried defer init on modal open?

**Comment by ad17633** [comment]
Thanks, but that doesn't work. Same behavior.

**Comment by lexkrstn** [comment]
Check out the last example of working with modals & tabs in [DEMO](https://lexkrstn.github.io/jquery-sked-tape/).
