### ISSUE TITLE
Add possibility to show events and timeline on local datetime

### ISSUE THREAD

**Issue by tokidoki11** [lexkrstn/jquery-sked-tape#11]
Events and timeline are only showing in UTC as for now

Adding boolean option flag like isShowInOffset and set the timeline accordingly

**Comment by tokidoki11** [comment]
I made a pull request for this :)
see #12

**Comment by 7tomas7** [comment]
@tokidoki11   Thanks :)

**Comment by lexkrstn** [comment]
It's now the default behavior in v2. Since now all the dates should be specified in current locale.
