### ISSUE TITLE
Add more explanation for tzOffset in README.md

### ISSUE THREAD

**Issue by david-learner** [lexkrstn/jquery-sked-tape#13]
First so thank you for this project.

tzOffset is based minute
At first, I confused when I set tzOffset 9. "Why don't appear any chages?"
When I saw SkedTape.js internal, I knew it. tzOffset is working for minute.
So If you ok to add a little mention for tzOffset. that is good to other people.

**Comment by tokidoki11** [comment]
Apparently it's the standard
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset

I was confused as well with the params :))

**Comment by david-learner** [comment]
> Apparently it's the standard
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset
> 
> I was confused as well with the params :))

Thank you !
