### ISSUE TITLE
Is it possible to resize part of the timesheet so that the scroll bar is not displayed?

### ISSUE THREAD

**Issue by eneko0513** [lexkrstn/jquery-sked-tape#16]
Hello lexkrstn.
Your library is very useful.

But I would like to ask for advice.
Please let me know if you can.

When the display range is exceeded, scroll bars are automatically displayed on the time sheet.

Is it possible to reduce this scroll bar to an invisible size?

The purpose is to browse timesheets without scrolling in a fixed sized browser.
Scrollbars are displayed when displaying information for one day, so I would like to solve this.

Thank you.

**Comment by lexkrstn** [comment]
Hi, eneko0513.
No, it currently is not possible. There is a minimum scale level set up, reducing which will break the layout.

**Comment by eneko0513** [comment]
Thank you lexkrstn.
OK.

I changed the CSS to get closer to the purpose.

Thank you for your reply.
