### ISSUE TITLE
Date tape is still shown in UTC while event is default to GMT

### ISSUE THREAD

**Issue by tokidoki11** [lexkrstn/jquery-sked-tape#19]
I know we can override the formatter, but for the sake of similarities should we change to LocateDateString by default as well?
Suggesting this change
using localeDate with en-US as default
```
date: function (date, endian, delim) {
	endian = endian || 'm';
	var nums = date.toLocaleDateString("en-US").split('/');
	nums = endian === 'l' ? [parseInt(nums[1]), parseInt(nums[0]), nums[2]] : nums;
	return nums.join(delim || (endian === 'm' ? '/' : '.'));
},
```

**Comment by lexkrstn** [comment]
Thanks for the observation! Just missed that when was switching to locale dates. Fixed in 2.2.2
