### ISSUE TITLE
change the time zone

### ISSUE THREAD

**Issue by aliajmat** [lexkrstn/jquery-sked-tape#2]
its always a good idea that developer can set there own time zone or there's clients time zone.
please update something to set the time zone for GMT

**Comment by lexkrstn** [comment]
There is the non-documented yet constructor option `tzOffset`, that affects time indicator line position.
You can see how it works in the last example of the [DEMO](https://lexkrstn.github.io/jquery-sked-tape/).

**Comment by aliajmat** [comment]
🤓 well, I have updated the sked-tape js. And do some changes to set it to my time zone and its working like a charms. 

Thanks.
