### ISSUE TITLE
Please tell me about the display speed problem and the export function.

### ISSUE THREAD

**Issue by eneko0513** [lexkrstn/jquery-sked-tape#23]
Hi, lexkrstn.

Your library is very useful.
However, there are some problems.
Can you give me an idea?

There are two problems.

No.1 is a display speed issue.
I want to put out a user time tape for 20,000 lines.

However, it takes more than 30 minutes to display.

Is there a way to improve the display speed?
There is data to display in advance.
Time is taking here.
>> $ sked2.appendTo ('# TestContainer'). skedTape ('render');

No.2 is about the export function.
I want to output the contents in the form of an excel graph when I press a button on the screen.
Or, I want to output the area as an image.
Does lexkrstn have any plans to add an export function in the future?

**Comment by lexkrstn** [comment]
Hi, @eneko0513. Good question.

1. There are a lot of improvements have to be done to speed up the rendering. It's far from perfect now and it implies a great deal of redesign work. In fact I intend to rewrite the whole code in pure JS to be able to use it seamlessly in my Vue projects too. But currently just can't say when I'll get around to it.

2. In short, no. There are plenty of third-party libraries to render html to image, you should consider using one of them.
