### ISSUE TITLE
How to change the background color of one event

### ISSUE THREAD

**Issue by rst-geruliang** [lexkrstn/jquery-sked-tape#3]
Hi,
I want to know how to change the background color of an event.
If it can, can you tell me how to set the background color of an event.
If it can't, please update something to set it
Thanks

**Comment by lexkrstn** [comment]
It's possible by setting the `className` property of an event. E.g.: 
```javascript
$skedTape.addEvent({
    ...
    className: 'sked-tape__event--special'
});
```
Assuming there is somewhere in css something like this:
```css
.sked-tape__event--special { background-color: red; }
```

**Comment by rst-geruliang** [comment]
Thank you very much.
It works.
And I also want to know can it fix the time title bar and the bottom when the timeline is so higher that vertical scroll is displayed
